/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6uGI7XcswmC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex min-h-screen w-full">
      <aside className="hidden md:flex flex-col items-center bg-background border-r px-4 py-6 gap-4">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <Music2Icon className="w-8 h-8 text-primary" />
          <span className="sr-only">Music Platform</span>
        </Link>
        <nav className="flex flex-col items-center gap-2">
          <Link
            href="#"
            className="flex items-center justify-center w-10 h-10 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <HomeIcon className="w-5 h-5" />
            <span className="sr-only">Home</span>
          </Link>
          <Link
            href="#"
            className="flex items-center justify-center w-10 h-10 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <SearchIcon className="w-5 h-5" />
            <span className="sr-only">Search</span>
          </Link>
          <Link
            href="#"
            className="flex items-center justify-center w-10 h-10 rounded-full bg-primary text-primary-foreground"
            prefetch={false}
          >
            <ExpandIcon className="w-5 h-5" />
            <span className="sr-only">Explore</span>
          </Link>
          <Link
            href="#"
            className="flex items-center justify-center w-10 h-10 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <LibraryIcon className="w-5 h-5" />
            <span className="sr-only">Library</span>
          </Link>
        </nav>
      </aside>
      <div className="flex-1 flex flex-col">
        <header className="bg-background border-b px-4 py-3 flex items-center justify-between md:hidden">
          <Link href="#" className="flex items-center" prefetch={false}>
            <Music2Icon className="w-6 h-6 text-primary" />
            <span className="sr-only">Music Platform</span>
          </Link>
          <nav className="flex items-center gap-4">
            <Link
              href="#"
              className="flex items-center justify-center w-8 h-8 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
              prefetch={false}
            >
              <HomeIcon className="w-5 h-5" />
              <span className="sr-only">Home</span>
            </Link>
            <Link
              href="#"
              className="flex items-center justify-center w-8 h-8 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
              prefetch={false}
            >
              <SearchIcon className="w-5 h-5" />
              <span className="sr-only">Search</span>
            </Link>
            <Link
              href="#"
              className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground"
              prefetch={false}
            >
              <ExpandIcon className="w-5 h-5" />
              <span className="sr-only">Explore</span>
            </Link>
            <Link
              href="#"
              className="flex items-center justify-center w-8 h-8 rounded-full text-muted-foreground hover:bg-muted hover:text-foreground"
              prefetch={false}
            >
              <LibraryIcon className="w-5 h-5" />
              <span className="sr-only">Library</span>
            </Link>
          </nav>
        </header>
        <main className="flex-1 overflow-auto">
          <section className="px-4 py-8 md:px-6 md:py-12">
            <h2 className="text-2xl font-bold mb-4">Explore Artists</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              {[...Array(10)].map((_, i) => (
                <Link
                  key={i}
                  href="#"
                  className="flex flex-col items-center gap-2 hover:bg-muted rounded-md p-4"
                  prefetch={false}
                >
                  <img
                    src="/placeholder.svg"
                    width="120"
                    height="120"
                    alt={`Artist ${i + 1}`}
                    className="rounded-full"
                    style={{ aspectRatio: "120/120", objectFit: "cover" }}
                  />
                  <div className="text-sm font-medium text-center">Artist {i + 1}</div>
                </Link>
              ))}
            </div>
          </section>
          <section className="px-4 py-8 md:px-6 md:py-12 bg-muted">
            <h2 className="text-2xl font-bold mb-4">Top Charts</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {[...Array(8)].map((_, i) => (
                <Card key={i} className="p-4">
                  <div className="flex items-center gap-4">
                    <img
                      src="/placeholder.svg"
                      width="64"
                      height="64"
                      alt={`Track ${i + 1}`}
                      className="rounded"
                      style={{ aspectRatio: "64/64", objectFit: "cover" }}
                    />
                    <div>
                      <div className="text-lg font-medium">Track {i + 1}</div>
                      <div className="text-sm text-muted-foreground">Artist {i + 1}</div>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          </section>
        </main>
      </div>
    </div>
  )
}

function ExpandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 21-6-6m6 6v-4.8m0 4.8h-4.8" />
      <path d="M3 16.2V21m0 0h4.8M3 21l6-6" />
      <path d="M21 7.8V3m0 0h-4.8M21 3l-6 6" />
      <path d="M3 7.8V3m0 0h4.8M3 3l6 6" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  )
}


function Music2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
